# Generated by Django 4.2.1 on 2023-05-04 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("temperature", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("description", models.CharField(max_length=80)),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
