# Generated by Django 4.2.1 on 2023-05-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherinfo_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
